#!/usr/bin/env bash
# Write a shell script that takes a path, and confirms if it is a directory or not. If it is a directory list all files in that directory, if not ask the user to give the file path of a directory.  Expected output: List of files in the directory path that was provided

# ask the path
echo "Enter the path:"
#  takes the path and put into path varibale
read -r path

# confirms if it is not a directory
if [ ! -d "$path" ]; then
    # ask the user to give the file path of a directory
    echo "Pleae broh! Give us a directory"
else
    # if previous condition is not verified, so the path is a diretcory
    # List of files in the directory path that was provided
    ls "$path"
fi
