#!/usr/bin/env bash

#Generate two random numbers
NUM1=$RANDOM
NUM2=$RANDOM

#Print of these numbers and their square roots
echo "The first random number is $NUM1"
ROOT1=`echo "scale=0;sqrt($NUM1)"|bc`
echo "The square root is $ROOT1"

echo "The first random number is $NUM2"
ROOT2=`echo "scale=0;sqrt($NUM2)"|bc`
echo "The square root is $ROOT2"

#Print the sum of their square roots
SUM=$(($ROOT1+$ROOT2))
echo "The sum of their square roots is $SUM"
